trigger:
  - dev
  - develop
  - master
  - cicd

resources:
  repositories:
    - repository: Pipelines
      type: git
      name: "Siigo/Siigo.Pipeline"

extends:
  template: gateway/gateway-pipeline.yaml@Pipelines
  parameters:
    projectName: api-gateway-catalog
    environment: aks
    namespace: siigo-catalog