apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: krakend
spec:
  servers:
    - hosts:
        - pdk8s.siigo.com
      port:
        name: https
        number: 443
        protocol: HTTPS
      tls:
        mode: SIMPLE
        privateKey: /etc/istio/ingressgateway-certs/tls.key
        serverCertificate: /etc/istio/ingressgateway-certs/tls.crt
  selector:
    istio: ingressgateway
