apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: krakend
spec:
  servers:
    - hosts:
        - "*"
      port:
        name: http
        number: 8087
        protocol: HTTP
  selector:
    istio: ingressgateway
