apiVersion: v1
kind: Service
metadata:
  name: krakend
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: http
    port: 8000
    targetPort: 8080
    protocol: TCP
  selector:
    app: krakend
