# Default values for aks.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

siigo-chart:
  # can be Development, Production, Testing, Local
  env: Production

  envs:
    ASPNETCORE_ENVIRONMENT: Production

  secrets: {}

  replicaCount: 2

  # set configuration for api gateway when isApiGateway is true

  apiGateway:
    enabled: true

    prefix: catalog

    host:
      dns: '*'
      port: 8087
      protocol: HTTP
  # end config gateway

  image:
    repository: #argument in pipeline
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    port: 8087
    targetPort: 8087

  hpa:
    maxReplicas: 2
    minReplicas: 1
    targetCPUUtilizationPercentage: 70

  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

  podSecurityContext: {}
  # fsGroup: 2000

  securityContext:
    {}
    # capabilities:
    #   drop:
    #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

  nodeSelector: {}

  tolerations: []

  affinity: {}

  podDisruptionBugets:
    minAvailable: 50%

  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate

  outlierDetection:
    {}
    #baseEjectionTime: 120.000s
    #consecutiveErrors: 2
    #interval: 1.000s
    #maxEjectionPercent: 100

  podAnnotations: {}

  appsettings: {}
